### ISSUE TITLE
add progress indicator

### ISSUE THREAD

**Issue by naderio** [tunpixel/select-input#7]
inspired by https://material.angularjs.org/#/demo/material.components.autocomplete

**Comment by naderio** [comment]
done, progress is handled externally

**Comment by TunpixelCEO** [comment]
bravo

On Sat, Mar 21, 2015 at 3:23 PM, Nader Toukabri notifications@github.com
wrote:

> Closed #7 https://github.com/tunpixel/select-input/issues/7.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tunpixel/select-input/issues/7#event-261159584.

## 

Bassem Bouguerra, CEO
